name: McGuffog&Company
description: McGuffog&Company Software - AccuRaw, AccuRaw Monochrome, WinDat Opener, and pcdMagic for Photo CD
paginate: 5
paginate_path: "/blog/page:num/"
baseurl:

plugins: [jekyll-paginate]
